import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL,
});

interface AgentSeed {
  address: string;
  name: string;
  symbol: string | null;
  chain: string;
  tier: string;
  description: string;
  coreFunctions: string[];
  website: string | null;
  twitter: string | null;
  github: string | null;
  docs: string | null;
  image: string | null;
  // Trust signals
  onChainScore: number;
  offChainScore: number;
  // Market data (if available)
  marketCap: number | null;
  price: number | null;
  volume24h: number | null;
}

// Scoring formula: trust = 0.5 * onChain + 0.3 * offChain + 0.2 * humanScore(default 50)
function computeTrustScore(onChain: number, offChain: number, human: number = 50): { score: number; grade: string } {
  const score = Math.round(0.5 * onChain + 0.3 * offChain + 0.2 * human);
  let grade: string;
  if (score >= 90) grade = 'S';
  else if (score >= 80) grade = 'A';
  else if (score >= 70) grade = 'B';
  else if (score >= 60) grade = 'C';
  else if (score >= 40) grade = 'D';
  else grade = 'F';
  return { score, grade };
}

const agents: AgentSeed[] = [
  // ===== BASE (18) =====
  {
    address: 'aixbt-base',
    name: 'AIXBT',
    symbol: 'AIXBT',
    chain: 'base',
    tier: '2',
    description: 'Alpha signals and trading calls aggregated from 400+ KOLs. Second-ranked AI Agent on Virtuals Protocol.',
    coreFunctions: ['trading signals', 'alpha aggregation', 'KOL tracking', 'market analysis'],
    website: 'https://aixbt.tech',
    twitter: 'https://x.com/aixbt_agent',
    github: null,
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 60,
    marketCap: 18213764,
    price: 0.018,
    volume24h: null,
  },
  {
    address: 'virtual-protocol-base',
    name: 'Virtuals Protocol',
    symbol: 'VIRTUAL',
    chain: 'base',
    tier: '3',
    description: 'Agent launchpad with 21k+ tokenized AI agents. Largest AI agent ecosystem on Base.',
    coreFunctions: ['agent launchpad', 'tokenization', 'agent-to-agent commerce', 'revenue sharing'],
    website: 'https://virtuals.io',
    twitter: 'https://x.com/virtloprotocol',
    github: 'https://github.com/Virtual-Protocol',
    docs: 'https://whitepaper.virtuals.io',
    image: null,
    onChainScore: 82,
    offChainScore: 85,
    marketCap: 385220733,
    price: 0.586,
    volume24h: 52539038,
  },
  {
    address: 'luna-virtuals-base',
    name: 'Luna',
    symbol: 'LUNA',
    chain: 'base',
    tier: '2',
    description: 'Social + trading agent on Virtuals Protocol. One of the earliest viral AI agents.',
    coreFunctions: ['social engagement', 'autonomous trading', 'content creation'],
    website: null,
    twitter: 'https://x.com/luna_virtuals',
    github: null,
    docs: null,
    image: null,
    onChainScore: 50,
    offChainScore: 45,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'game-virtuals-base',
    name: 'GAME',
    symbol: 'GAME',
    chain: 'base',
    tier: '3',
    description: 'Agent behavior framework powering autonomous agent logic on Virtuals ecosystem.',
    coreFunctions: ['agent behavior engine', 'decision framework', 'agent orchestration'],
    website: null,
    twitter: 'https://x.com/game_virtuals',
    github: null,
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 50,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'spectral-base',
    name: 'Spectral',
    symbol: 'SPEC',
    chain: 'base',
    tier: '1',
    description: 'On-chain ML inference for code generation and DeFi automation.',
    coreFunctions: ['ML inference', 'code generation', 'DeFi automation', 'smart contract analysis'],
    website: 'https://spectral.finance',
    twitter: 'https://x.com/SpectralFi',
    github: 'https://github.com/Spectral-Finance',
    docs: 'https://docs.spectral.finance',
    image: null,
    onChainScore: 65,
    offChainScore: 70,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'based-agent-base',
    name: 'Based Agent',
    symbol: null,
    chain: 'base',
    tier: '3',
    description: "Coinbase's agent framework for creating wallets and executing on-chain transactions.",
    coreFunctions: ['wallet creation', 'transaction execution', 'agent framework'],
    website: 'https://www.coinbase.com/developer-platform',
    twitter: 'https://x.com/CoinbaseDev',
    github: 'https://github.com/coinbase/agentkit',
    docs: 'https://docs.cdp.coinbase.com',
    image: null,
    onChainScore: 85,
    offChainScore: 90,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'sekoia-base',
    name: 'Sekoia',
    symbol: 'SEKOIA',
    chain: 'base',
    tier: '2',
    description: 'Virtuals social agent for content creation and trading.',
    coreFunctions: ['social content', 'trading', 'community engagement'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 35,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'heyanon-base',
    name: 'Hey Anon',
    symbol: 'ANON',
    chain: 'base',
    tier: '1',
    description: 'AI DeFi protocol: swaps, bridging, yield strategies, lending — all via natural language.',
    coreFunctions: ['natural language swaps', 'cross-chain bridging', 'yield strategies', 'lending'],
    website: 'https://heyanon.ai',
    twitter: 'https://x.com/HeyAnonai',
    github: 'https://github.com/RealWagmi',
    docs: 'https://docs.heyanon.ai',
    image: null,
    onChainScore: 65,
    offChainScore: 70,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'moltbook-base',
    name: 'Moltbook',
    symbol: null,
    chain: 'base',
    tier: '3',
    description: 'Social layer for agent-to-agent interactions on Base.',
    coreFunctions: ['agent social network', 'agent-to-agent messaging'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 30,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'warden-base',
    name: 'Warden Protocol',
    symbol: 'WARDEN',
    chain: 'base',
    tier: '3',
    description: 'Agent infrastructure and security layer for securing agent transactions.',
    coreFunctions: ['agent security', 'transaction validation', 'key management'],
    website: 'https://wardenprotocol.org',
    twitter: 'https://x.com/waraborot',
    github: 'https://github.com/warden-protocol',
    docs: null,
    image: null,
    onChainScore: 60,
    offChainScore: 65,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'creatorbid-base',
    name: 'CreatorBid',
    symbol: 'CB',
    chain: 'base',
    tier: '3',
    description: 'AI agent marketplace for discovering and deploying agents.',
    coreFunctions: ['agent marketplace', 'agent discovery', 'agent deployment'],
    website: 'https://creatorbid.com',
    twitter: 'https://x.com/CreatorBid',
    github: null,
    docs: null,
    image: null,
    onChainScore: 45,
    offChainScore: 50,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'olaxbt-base',
    name: 'OlaXBT',
    symbol: 'OLAXBT',
    chain: 'base',
    tier: '2',
    description: 'Trading signals agent on Base chain.',
    coreFunctions: ['trading signals', 'market analysis'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 30,
    marketCap: 17433409,
    price: 0.075,
    volume24h: null,
  },
  {
    address: 'satoshi-ai-base',
    name: 'Satoshi AI Agent',
    symbol: null,
    chain: 'base',
    tier: '2',
    description: 'Bitcoin narrative-themed AI trading signals agent.',
    coreFunctions: ['trading signals', 'Bitcoin analysis'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 30,
    offChainScore: 25,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'cookie-dao-base',
    name: 'Cookie DAO',
    symbol: 'COOKIE',
    chain: 'multi',
    tier: '3',
    description: 'Agent analytics and data platform. Cross-chain trust data provider.',
    coreFunctions: ['agent analytics', 'data aggregation', 'trust metrics'],
    website: 'https://cookie.fun',
    twitter: 'https://x.com/cookiedotfun',
    github: null,
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 60,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'holoworld-base',
    name: 'Holoworld',
    symbol: null,
    chain: 'base',
    tier: '3',
    description: 'Agent creation platform on Base.',
    coreFunctions: ['agent creation', 'agent hosting'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 35,
    marketCap: 18655478,
    price: 0.054,
    volume24h: null,
  },
  {
    address: 'amiko-base',
    name: 'Amiko',
    symbol: 'AMIKO',
    chain: 'base',
    tier: '1',
    description: 'Personal AI agent that manages user preferences and DeFi interactions.',
    coreFunctions: ['personal agent', 'preference management', 'DeFi interaction'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 35,
    marketCap: 21621630,
    price: 0.027,
    volume24h: null,
  },
  {
    address: 'ai-rig-complex-base',
    name: 'AI Rig Complex',
    symbol: 'ARC',
    chain: 'base',
    tier: '3',
    description: 'Agent infrastructure powering other AI agents.',
    coreFunctions: ['agent infrastructure', 'agent orchestration'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 45,
    offChainScore: 50,
    marketCap: 90277732,
    price: 0.09,
    volume24h: null,
  },
  {
    address: 'venice-ai-base',
    name: 'Venice AI',
    symbol: 'VVV',
    chain: 'base',
    tier: '3',
    description: 'Private AI inference platform. Privacy-focused agent execution.',
    coreFunctions: ['private inference', 'agent execution', 'privacy'],
    website: 'https://venice.ai',
    twitter: 'https://x.com/VeniceAI',
    github: null,
    docs: null,
    image: null,
    onChainScore: 60,
    offChainScore: 65,
    marketCap: 167354373,
    price: 3.78,
    volume24h: 11539163,
  },

  // ===== SOLANA (16) =====
  {
    address: 'pippin-sol',
    name: 'Pippin',
    symbol: 'PIPPIN',
    chain: 'sol',
    tier: '1',
    description: 'Autonomous on-chain agent executing trades on Solana. $731M market cap despite experiment origins. ⚠️ ~80% supply in insider wallets per Bubblemap.',
    coreFunctions: ['autonomous trading', 'on-chain execution', 'Solana DeFi'],
    website: null,
    twitter: 'https://x.com/pippinlovesyou',
    github: null,
    docs: null,
    image: null,
    onChainScore: 45,
    offChainScore: 35,
    marketCap: 731347164,
    price: 0.734,
    volume24h: 59100333,
  },
  {
    address: 'griffain-sol',
    name: 'Griffain',
    symbol: 'GRIFFAIN',
    chain: 'sol',
    tier: '1',
    description: 'Solana agent for sniping, trading, and DCA. Direct fund management.',
    coreFunctions: ['token sniping', 'trading', 'DCA', 'fund management'],
    website: 'https://griffain.com',
    twitter: 'https://x.com/griffaindotcom',
    github: null,
    docs: null,
    image: null,
    onChainScore: 50,
    offChainScore: 45,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'elizaos-sol',
    name: 'ElizaOS (ai16z)',
    symbol: 'AI16Z',
    chain: 'sol',
    tier: '3',
    description: 'Agent framework + DAO powering most Solana AI agents. The backbone of Solana agent ecosystem.',
    coreFunctions: ['agent framework', 'DAO governance', 'agent deployment', 'multi-platform support'],
    website: 'https://elizaos.ai',
    twitter: 'https://x.com/ai16zdao',
    github: 'https://github.com/elizaOS',
    docs: 'https://elizaos.github.io/eliza/',
    image: null,
    onChainScore: 70,
    offChainScore: 80,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'goat-sol',
    name: 'GOAT',
    symbol: 'GOAT',
    chain: 'sol',
    tier: '2',
    description: 'The original viral AI agent meme token. First to prove AI agent narrative.',
    coreFunctions: ['meme agent', 'community engagement'],
    website: null,
    twitter: 'https://x.com/truth_terminal',
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 45,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'swarms-sol',
    name: 'Swarms',
    symbol: 'SWARMS',
    chain: 'sol',
    tier: '3',
    description: 'Multi-agent orchestration platform for coordinating agent swarms.',
    coreFunctions: ['multi-agent orchestration', 'swarm coordination', 'task distribution'],
    website: 'https://swarms.world',
    twitter: 'https://x.com/swabormsxorp',
    github: 'https://github.com/kyegomez/swarms',
    docs: 'https://docs.swarms.world',
    image: null,
    onChainScore: 50,
    offChainScore: 65,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'sendai-sol',
    name: 'SendAI',
    symbol: 'SEND',
    chain: 'sol',
    tier: '3',
    description: 'Solana Agent Kit — 50+ actions across 30+ protocols. Infrastructure for all Solana agents.',
    coreFunctions: ['agent toolkit', 'protocol integration', 'action library', 'cross-protocol execution'],
    website: 'https://sendai.fun',
    twitter: 'https://x.com/SendAI_',
    github: 'https://github.com/sendaifun/solana-agent-kit',
    docs: null,
    image: null,
    onChainScore: 65,
    offChainScore: 75,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'hive-sol',
    name: 'The Hive',
    symbol: 'HIVE',
    chain: 'sol',
    tier: '1',
    description: 'Modular DeFi proxy network for routing DeFi operations. Won Solana AI Hackathon top prize ($60k).',
    coreFunctions: ['DeFi proxy', 'operation routing', 'modular DeFi', 'strategy execution'],
    website: null,
    twitter: 'https://x.com/askthehive_ai',
    github: null,
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 60,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'arc-rig-sol',
    name: 'ARC (Rig Framework)',
    symbol: 'ARC',
    chain: 'sol',
    tier: '3',
    description: 'Rust-native agent framework for building and deploying AI agents on Solana.',
    coreFunctions: ['agent framework', 'Rust SDK', 'agent deployment', 'containerized execution'],
    website: 'https://arc.fun',
    twitter: 'https://x.com/arc_fun',
    github: 'https://github.com/0xPlaygrounds/rig',
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 70,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'zerebro-sol',
    name: 'Zerebro',
    symbol: 'ZEREBRO',
    chain: 'sol',
    tier: '2',
    description: 'Autonomous content + trading agent. ⚠️ CRITICAL: Co-founder controversy (May 2025) — suspected exit liquidity event.',
    coreFunctions: ['autonomous content', 'cross-chain trading', 'social media'],
    website: 'https://zerebro.org',
    twitter: 'https://x.com/0xzerebro',
    github: null,
    docs: null,
    image: null,
    onChainScore: 25,
    offChainScore: 15,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'kite-sol',
    name: 'Kite AI',
    symbol: 'KITE',
    chain: 'sol',
    tier: '3',
    description: 'AI data and agent network. Data layer for autonomous agents.',
    coreFunctions: ['data layer', 'agent network', 'AI data provisioning'],
    website: 'https://kiteai.com',
    twitter: 'https://x.com/KiteAI',
    github: null,
    docs: null,
    image: null,
    onChainScore: 50,
    offChainScore: 55,
    marketCap: 438980675,
    price: 0.244,
    volume24h: 121563992,
  },
  {
    address: 'sentient-sol',
    name: 'Sentient',
    symbol: 'SENT',
    chain: 'sol',
    tier: '3',
    description: 'Open AI agent protocol for agent interoperability.',
    coreFunctions: ['agent interoperability', 'open protocol', 'agent communication'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 45,
    marketCap: 170443908,
    price: 0.024,
    volume24h: 53758145,
  },
  {
    address: 'singularry-sol',
    name: 'Singularry',
    symbol: null,
    chain: 'sol',
    tier: '3',
    description: 'Agent marketplace on Solana for agent discovery.',
    coreFunctions: ['agent marketplace', 'agent discovery'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 30,
    offChainScore: 30,
    marketCap: 46069461,
    price: 0.046,
    volume24h: null,
  },
  {
    address: 'wayfinder-sol',
    name: 'Wayfinder',
    symbol: 'PROMPT',
    chain: 'sol',
    tier: '1',
    description: 'On-chain agent routing. Routes tasks to the best available agent.',
    coreFunctions: ['agent routing', 'task delegation', 'agent discovery'],
    website: 'https://wayfinder.ai',
    twitter: 'https://x.com/AIWayfinder',
    github: null,
    docs: null,
    image: null,
    onChainScore: 50,
    offChainScore: 55,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'hive-intel-sol',
    name: 'Hive Intelligence',
    symbol: null,
    chain: 'sol',
    tier: '3',
    description: 'Real-time on-chain data feed for AI agents. Partnered with ARC.',
    coreFunctions: ['real-time data', 'on-chain indexing', 'agent data feed'],
    website: null,
    twitter: 'https://x.com/Hive_Intel',
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 45,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'crossmint-goat-sol',
    name: 'Crossmint GOAT Toolkit',
    symbol: null,
    chain: 'sol',
    tier: '3',
    description: 'Agent development tools from Crossmint for building on Solana.',
    coreFunctions: ['agent dev tools', 'wallet management', 'NFT minting'],
    website: 'https://crossmint.com',
    twitter: 'https://x.com/crossmint',
    github: 'https://github.com/AugmentHQ/goat',
    docs: 'https://docs.crossmint.com',
    image: null,
    onChainScore: 70,
    offChainScore: 75,
    marketCap: null,
    price: null,
    volume24h: null,
  },

  // ===== BNB (10) =====
  {
    address: 'myshell-bnb',
    name: 'MyShell',
    symbol: 'SHELL',
    chain: 'bnb',
    tier: '3',
    description: 'Build, share, and own AI apps. 500k daily users. Highest-funded AI agent project on BNB.',
    coreFunctions: ['AI app platform', 'agent creation', 'agent marketplace', 'voice agents'],
    website: 'https://myshell.ai',
    twitter: 'https://x.com/myshell_ai',
    github: 'https://github.com/myshell-ai',
    docs: 'https://docs.myshell.ai',
    image: null,
    onChainScore: 70,
    offChainScore: 80,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'chaingpt-bnb',
    name: 'ChainGPT',
    symbol: 'CGPT',
    chain: 'bnb',
    tier: '1',
    description: 'Smart contract generation, on-chain analytics, AI trading models, and AML solutions on BSC/opBNB.',
    coreFunctions: ['smart contract gen', 'on-chain analytics', 'AI trading', 'AML tools'],
    website: 'https://chaingpt.org',
    twitter: 'https://x.com/Chain_GPT',
    github: 'https://github.com/ChainGPT-org',
    docs: 'https://docs.chaingpt.org',
    image: null,
    onChainScore: 65,
    offChainScore: 70,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'nfp-bnb',
    name: 'NFP',
    symbol: 'NFP',
    chain: 'bnb',
    tier: '3',
    description: 'AI-generated content platform on BNB Chain.',
    coreFunctions: ['AI content generation', 'NFT creation'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 45,
    offChainScore: 40,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'gata-bnb',
    name: 'Gata',
    symbol: 'GATA',
    chain: 'bnb',
    tier: '3',
    description: 'AI data labeling platform on BNB Chain.',
    coreFunctions: ['data labeling', 'AI training data', 'data quality'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 40,
    offChainScore: 40,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'termix-bnb',
    name: 'TermiX',
    symbol: null,
    chain: 'bnb',
    tier: '3',
    description: 'AI agent terminal on BNB Chain.',
    coreFunctions: ['agent terminal', 'agent execution'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 30,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'meet48-bnb',
    name: 'MEET 48',
    symbol: null,
    chain: 'bnb',
    tier: '3',
    description: 'AI entertainment agents on BNB Chain.',
    coreFunctions: ['AI entertainment', 'virtual idols'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 35,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'alaya-bnb',
    name: 'Alaya',
    symbol: null,
    chain: 'bnb',
    tier: '3',
    description: 'AI data collection platform on BNB Chain.',
    coreFunctions: ['data collection', 'data integrity'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 35,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'bankrcoin-bnb',
    name: 'BankrCoin',
    symbol: 'BANKR',
    chain: 'bnb',
    tier: '1',
    description: 'DeFi agent on BSC for fund management.',
    coreFunctions: ['DeFi automation', 'fund management'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 30,
    marketCap: 58136699,
    price: 0.00058,
    volume24h: null,
  },
  {
    address: 'delysium-bnb',
    name: 'Delysium (Lucy OS)',
    symbol: 'AGI',
    chain: 'bnb',
    tier: '3',
    description: 'Plug-and-play agent interface for DeFi, gaming, NFTs. Partnerships with Google, Microsoft, NVIDIA.',
    coreFunctions: ['DeFi agents', 'gaming NPCs', 'NFT tools', 'cross-chain services'],
    website: 'https://delysium.com',
    twitter: 'https://x.com/The_Delysium',
    github: null,
    docs: null,
    image: null,
    onChainScore: 55,
    offChainScore: 65,
    marketCap: 25942439,
    price: 0.011,
    volume24h: null,
  },

  // ===== ARC Chain (6) =====
  {
    address: 'arc-reactor',
    name: 'ARC Reactor',
    symbol: 'ARC',
    chain: 'arc',
    tier: '2',
    description: 'AI news curation and instant summaries on ARC chain.',
    coreFunctions: ['news curation', 'AI summaries', 'content discovery'],
    website: 'https://arc.ai',
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 40,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'arc-pay-agents',
    name: 'ARC Pay Agents',
    symbol: null,
    chain: 'arc',
    tier: '1',
    description: 'Autonomous subscription payment agents on ARC blockchain using native USDC.',
    coreFunctions: ['subscription payments', 'USDC automation', 'recurring payments'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 30,
    offChainScore: 25,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'arc-trading-agents',
    name: 'ARC Trading Agents',
    symbol: null,
    chain: 'arc',
    tier: '1',
    description: 'On-chain trading strategy agents on ARC.',
    coreFunctions: ['trading strategies', 'asset management'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 25,
    offChainScore: 20,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'arc-nocode-platform',
    name: 'ARC No-Code Platform',
    symbol: null,
    chain: 'arc',
    tier: '3',
    description: 'No-code platform for building and deploying autonomous AI agents on ARC.',
    coreFunctions: ['no-code builder', 'agent deployment', 'DeFi automation'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 25,
    offChainScore: 25,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'hive-intel-arc',
    name: 'Hive Intelligence x ARC',
    symbol: null,
    chain: 'arc',
    tier: '3',
    description: 'Real-time blockchain data bridge for AI agents on ARC chain.',
    coreFunctions: ['real-time data', 'blockchain bridge', 'agent data feed'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 35,
    offChainScore: 40,
    marketCap: null,
    price: null,
    volume24h: null,
  },
  {
    address: 'arc-defi-agents',
    name: 'ARC DeFi Agents',
    symbol: null,
    chain: 'arc',
    tier: '1',
    description: 'Asset management automation agents on ARC chain.',
    coreFunctions: ['asset management', 'DeFi automation', 'strategy execution'],
    website: null,
    twitter: null,
    github: null,
    docs: null,
    image: null,
    onChainScore: 25,
    offChainScore: 20,
    marketCap: null,
    price: null,
    volume24h: null,
  },
];

async function main() {
  console.log('🌱 Seeding 50 AI agents...\n');

  let created = 0;
  let updated = 0;

  for (const agent of agents) {
    const { score, grade } = computeTrustScore(agent.onChainScore, agent.offChainScore);

    const data = {
      name: agent.name,
      description: agent.description,
      image: agent.image,
      website: agent.website,
      category: 'm/ai-agents',
      chain: agent.chain,
      symbol: agent.symbol,
      tier: agent.tier,
      coreFunctions: JSON.stringify(agent.coreFunctions),
      twitter: agent.twitter,
      github: agent.github,
      docs: agent.docs,
      trustScore: score,
      trustGrade: grade,
      onChainScore: agent.onChainScore,
      offChainScore: agent.offChainScore,
      humanScore: 50, // default until reviews come in
      trustUpdatedAt: new Date(),
      marketCap: agent.marketCap,
      price: agent.price,
      volume24h: agent.volume24h,
      status: 'active',
    };

    const existing = await prisma.project.findUnique({ where: { address: agent.address } });

    if (existing) {
      await prisma.project.update({ where: { address: agent.address }, data });
      updated++;
    } else {
      await prisma.project.create({ data: { address: agent.address, slug: agent.address, ...data } });
      created++;
    }

    console.log(`  ${grade} ${score}/100 — ${agent.name} (${agent.chain})`);
  }

  console.log(`\n✅ Done: ${created} created, ${updated} updated`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
